spring:
  init:
    mode: never
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/jira
    username: jira
    password: JiraRush
  liquibase:
    changeLog: "classpath:db/changelog.sql"
    sql:
      init:
        mode: always
        data-locations: classpath:data4dev/data.sql